config/routes.rb
Sampl::Application.routes.draw do
      get "users/new"

  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/kontakt', to: 'static_pages#kontakt', via: 'get'
  match '/signin',  to: 'static_pages#signin',  via: 'get'
  match '/signup',  to: 'static_pages#signup',  via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def kontakt
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://etalux.pl/">Etalux.pl</a>
    by Hubert Kalinowski
  </small>
  <nav>
    <ul>
      <li><%= link_to "O nas",  about_path  %></li>
      <li><%= link_to "Kontakt", kontakt_path  %></li>
      <li><%= link_to "Aktualności", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Etalux", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Strona główna",    root_path %></li>
          <li><%= link_to "Pomoc", help_path %></li>
          <li><%= link_to "Zaloguj się", '#' %></li>
          <li><%= link_to "Kontakt", kontakt_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>O nas</h1>
<p>
   	
ISTNIEJEMY od 1991r. Produkujemy bramy garażowe, segmentowe, rolowane, bramy przemysłowe, rolety zewnętrzne oraz różnego rodzaju rolety tekstylne i żaluzje. Prowadzimy również sprzedaż hurtową elementów do ich produkcji. Konsekwentna strategia firmy oraz wieloletnie doświadczenie w tej branży pozwoliło nam na osiągnięcie wysokiej pozycji na rynku krajowym i zagranicznym. W wyrobach własnych, które stanowią 90% naszej oferty, stosujemy komponenty pochodzące od najlepszych europejskich dostawców. Dzięki temu możemy zaproponować Państwu nie tylko ciekawą ofertę, ale również bardzo przystępną cenę, wysoką jakość zarówno samych produktów jak i montaż oraz serwis zainstalowanych urządzeń. Ciągle poszerzany asortyment oraz sukcesywnie zwiększająca się ilość zleceń potwierdzają słuszność obranego przez nas kilkanaście lat temu kierunku.
Sprawdź naszą ofertę. Zapraszamy! 
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  W razie problemów technicznych dzwonić pod numer 515446771
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Witaj w naszym serwisie!</h1>

  <h2>
    Oto nasza strona na której <br /> znajdziesz cennik oraz dane kontaktowe, <br /> jak również złożysz zamówienia!
  </h2>

  <%= link_to "Zarejestruj się!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/kontakt.html.erb
<% provide(:title, 'Kontakt') %>
<h1>Kontakt</h1>
<p>
42-200 CZĘSTOCHOWA <br />
ul. Św. Augustyna 27 <br />
Tel/Fax +48 34 365 63 58 <br />
email: biuro@etalux.pl <br />
<a href="http://etalux.pl/">Strona firmy ETALUX</a>
</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>